name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: BASE_URL=https://tunes.plnt.earth npm run sitemap
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          git add sitemap.xml
          git commit -m "Update sitemap [skip ci]" || echo "No changes"
          git push
